version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    hostname: influxdb
    environment:
      INFLUX_DB: "thermometer"
      INFLUXDB_USER: "thermometer"
      INFLUXDB_USER_PASSWORD: "thermometer"
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    links:
      - influxdb:influxdb
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  influxdb-data:
  grafana-data:
